spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo19oo22021
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  mvc:
     contentnegotiation:
             media-types:
                     pdf: application/pdf
             favor-parameter: true